"""empty message

Revision ID: cf5f6f1b902b
Revises: 
Create Date: 2024-02-01 00:33:57.031736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5f6f1b902b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('characters_birth_year', sa.String(length=20), nullable=False),
    sa.Column('characters_eye', sa.String(length=25), nullable=False),
    sa.Column('characters_hair_color', sa.String(length=20), nullable=False),
    sa.Column('characters_height', sa.Integer(), nullable=False),
    sa.Column('characters_name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_climate', sa.Integer(), nullable=False),
    sa.Column('planet_gravity', sa.Integer(), nullable=False),
    sa.Column('planet_name', sa.String(length=250), nullable=False),
    sa.Column('planet_population', sa.Integer(), nullable=False),
    sa.Column('planet_terrain', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planet_name')
    )
    op.create_table('starship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starship_cost_in_Credit', sa.Integer(), nullable=False),
    sa.Column('starship_length', sa.Integer(), nullable=False),
    sa.Column('starship_manufacturer', sa.String(length=250), nullable=False),
    sa.Column('starship_model', sa.String(length=250), nullable=False),
    sa.Column('starship_name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('tel', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_characters', sa.Integer(), nullable=True),
    sa.Column('id_planet', sa.Integer(), nullable=True),
    sa.Column('id_starship', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_characters'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['id_planet'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['id_starship'], ['starship.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('user')
    op.drop_table('starship')
    op.drop_table('planet')
    op.drop_table('characters')
    # ### end Alembic commands ###
